title: GTC Time Stage Forecasting v1
type: community
group: Time Series Analysis
image: /static/templates/time-series-forecasting.png
details: <h1>Prepare training data for GTC time stage forecasting models</h1>
config: |
  <View>
      <Header value="这次模拟结果如何？"/>
      <Choices name="quality" toName="ts" choice="single">
          <Choice alias="G" value="Good" hotkey="g"/>
          <Choice alias="M" value="Mediocre" hotkey="m"/>
          <Choice alias="B" value="Bad" hotkey="b"/>
      </Choices>
  
      <!-- Control tag for region labels -->
      <Header value="请在该模拟输出序列上标注出其阶段"/>
      <TimeSeriesLabels name="label" toName="ts">
          <Label value="linear" background="#5a95e2" hotkey="l"/>
          <Label value="nonlinear" background="#c27ee2" hotkey="n"/>
          <Label value="saturation" background="#5bcc1e" hotkey="s"/>
          <Label value="vanish" background="#d3380d"/>
          <Label value="divergence" background="#3f3f3f"/>
      </TimeSeriesLabels> 
  
      <!-- Object tag for time series data source -->
      <TimeSeries name="ts" valueType="json" value="$ts" timeColumn="time" overviewWidth="100%">
          <!-- default-height=200, ref: https://app.heartex.ai/docs/tags/timeseries.html#Channel -->
          <Channel column="chi_i" legend="chi_i" displayFormat=".3~e" height="300" strokeWidth="1.5"/>
          <Channel column="d_i" legend="D_i" displayFormat=".3~e" strokeWidth="1.5"/>
          <Channel column="logphirms" legend="logphirms" displayFormat=".3~e" height="300" strokeWidth="1.5"/>
      </TimeSeries>
  </View>
